export type MockStringData = {
  testCaseId: string
  scenario: string
  emailAddress1?: string
  emailAddress2?: string
  emailAddress3?: string
  password1?: string
  password2?: string
  password3?: string
  age?: string
  date?: string
  message1?: string
  message2?: string
  message3?: string
  oldGender?: string
  newGender?: string
  dob?: string
  firstName?: string
  lastName?: string
  phoneNumber?: string
  phoneNumber1?: string
  phoneNumber2?: string
  streetAddress?: string
  female?: string
  male?: string
  name?: string
  city?: string
  state?: string
  zipCode?: string
  option1?: string
  option2?: string
  option3?: string
  option4?: string
  option5?: string
  option6?: string
  option7?: string
  option8?: string
  option9?: string
  option10?: string
}